export enum Category {
  telegram = 'telegram',
  spam = 'spam',
  job = 'job',
  freelance = 'freelance',
  consulting = 'consulting',
  pricing = 'pricing',
  partnership = 'partnership',
  investment = 'investment',
  hiring = 'hiring',
  interview = 'interview',
  speaking = 'speaking',
  media = 'media',
  support = 'support',
  review = 'review',
  decision = 'decision',
  product = 'product',
  access = 'access',
  resume = 'resume',
  portfolio = 'portfolio',
  articles = 'articles',
  life = 'life',
  intro = 'intro',
  greeting = 'greeting',
  followup = 'followup',
  gratitude = 'gratitude',
  clarification = 'clarification',
  none = 'none',
  technology = 'technology',
}

const CATEGORY_SOURCE_MAP: Partial<Record<Category, Category>> = {
  [Category.articles]: Category.articles,
  [Category.technology]: Category.articles,
  [Category.support]: Category.articles,
  [Category.speaking]: Category.articles,
  [Category.decision]: Category.portfolio,
  [Category.portfolio]: Category.portfolio,
  [Category.product]: Category.portfolio,
  [Category.media]: Category.portfolio,
  [Category.resume]: Category.resume,
  [Category.pricing]: Category.resume,
  [Category.interview]: Category.resume,
  [Category.hiring]: Category.resume,
  [Category.job]: Category.resume,
  [Category.freelance]: Category.resume,
  [Category.consulting]: Category.resume,
  [Category.partnership]: Category.resume,
  [Category.investment]: Category.resume,
  [Category.intro]: Category.resume,
  [Category.greeting]: Category.resume,
  [Category.life]: Category.resume,
  [Category.review]: Category.telegram,
  [Category.access]: Category.telegram,
  [Category.telegram]: Category.telegram,
  [Category.spam]: Category.none,
  [Category.gratitude]: Category.none,
  [Category.none]: Category.none,
  [Category.clarification]: Category.clarification,
  [Category.followup]: Category.followup,
};

export function getCategoryByDetectedCategory(
  detectedCategory: Category,
): Category {
  return CATEGORY_SOURCE_MAP[detectedCategory] ?? Category.none;
}
