import { readFileSync } from 'fs';
import { resolve } from 'path';

export enum GetConstantKey {
  QuestionTransformer_transformQuestion_1 = 'QuestionTransformer_transformQuestion_1',
  QuestionTransformer_transformQuestion_2 = 'QuestionTransformer_transformQuestion_2',
  QuestionTransformer_transformQuestion_3 = 'QuestionTransformer_transformQuestion_3',
  LlmChunkProcessor_semanticTemplate = 'LlmChunkProcessor_semanticTemplate',
  LlmChunkProcessor_simpleTemplate = 'LlmChunkProcessor_simpleTemplate',
  Prompt_friendlyFoundTemplate = 'Prompt_friendlyFoundTemplate',
  Prompt_friendlyNotFoundTemplate = 'Prompt_friendlyNotFoundTemplate',
  Prompt_contextualRewriteTemplate = 'Prompt_contextualRewriteTemplate',
  Prompt_contextualRewriteHistoryTemplate = 'Prompt_contextualRewriteHistoryTemplate',
  Prompt_minimalTransformationTemplate = 'Prompt_minimalTransformationTemplate',
  Prompt_minimalTransformationHistoryTemplate = 'Prompt_minimalTransformationHistoryTemplate',
  Prompt_dialogSummaryTemplate = 'Prompt_dialogSummaryTemplate',
  Prompt_finalAnswerTemplate = 'Prompt_finalAnswerTemplate',
  Prompt_documentAnalysisTemplate = 'Prompt_documentAnalysisTemplate',
  DialogManager_historyTemplate = 'DialogManager_historyTemplate',
  // Category prompt templates
  CategoryPrompt_telegram = 'CategoryPrompt_telegram',
  CategoryPrompt_spam = 'CategoryPrompt_spam',
  CategoryPrompt_job = 'CategoryPrompt_job',
  CategoryPrompt_freelance = 'CategoryPrompt_freelance',
  CategoryPrompt_consulting = 'CategoryPrompt_consulting',
  CategoryPrompt_pricing = 'CategoryPrompt_pricing',
  CategoryPrompt_partnership = 'CategoryPrompt_partnership',
  CategoryPrompt_investment = 'CategoryPrompt_investment',
  CategoryPrompt_hiring = 'CategoryPrompt_hiring',
  CategoryPrompt_interview = 'CategoryPrompt_interview',
  CategoryPrompt_speaking = 'CategoryPrompt_speaking',
  CategoryPrompt_media = 'CategoryPrompt_media',
  CategoryPrompt_support = 'CategoryPrompt_support',
  CategoryPrompt_review = 'CategoryPrompt_review',
  CategoryPrompt_decision = 'CategoryPrompt_decision',
  CategoryPrompt_product = 'CategoryPrompt_product',
  CategoryPrompt_access = 'CategoryPrompt_access',
  CategoryPrompt_resume = 'CategoryPrompt_resume',
  CategoryPrompt_portfolio = 'CategoryPrompt_portfolio',
  CategoryPrompt_articles = 'CategoryPrompt_articles',
  CategoryPrompt_life = 'CategoryPrompt_life',
  CategoryPrompt_intro = 'CategoryPrompt_intro',
  CategoryPrompt_followup = 'CategoryPrompt_followup',
  CategoryPrompt_gratitude = 'CategoryPrompt_gratitude',
  CategoryPrompt_clarification = 'CategoryPrompt_clarification',
  CategoryPrompt_none = 'CategoryPrompt_none',
  CategoryPrompt_technology = 'CategoryPrompt_technology',
  // Category description templates
  CategoryDescription_telegram = 'CategoryDescription_telegram',
  CategoryDescription_spam = 'CategoryDescription_spam',
  CategoryDescription_job = 'CategoryDescription_job',
  CategoryDescription_freelance = 'CategoryDescription_freelance',
  CategoryDescription_consulting = 'CategoryDescription_consulting',
  CategoryDescription_pricing = 'CategoryDescription_pricing',
  CategoryDescription_partnership = 'CategoryDescription_partnership',
  CategoryDescription_investment = 'CategoryDescription_investment',
  CategoryDescription_hiring = 'CategoryDescription_hiring',
  CategoryDescription_interview = 'CategoryDescription_interview',
  CategoryDescription_speaking = 'CategoryDescription_speaking',
  CategoryDescription_media = 'CategoryDescription_media',
  CategoryDescription_support = 'CategoryDescription_support',
  CategoryDescription_review = 'CategoryDescription_review',
  CategoryDescription_decision = 'CategoryDescription_decision',
  CategoryDescription_product = 'CategoryDescription_product',
  CategoryDescription_access = 'CategoryDescription_access',
  CategoryDescription_resume = 'CategoryDescription_resume',
  CategoryDescription_portfolio = 'CategoryDescription_portfolio',
  CategoryDescription_articles = 'CategoryDescription_articles',
  CategoryDescription_life = 'CategoryDescription_life',
  CategoryDescription_intro = 'CategoryDescription_intro',
  CategoryDescription_followup = 'CategoryDescription_followup',
  CategoryDescription_gratitude = 'CategoryDescription_gratitude',
  CategoryDescription_clarification = 'CategoryDescription_clarification',
  CategoryDescription_none = 'CategoryDescription_none',
  CategoryDescription_technology = 'CategoryDescription_technology',
  // LLM Chunk Processor regex patterns
  LlmChunkProcessor_authorMessageHeader = 'LlmChunkProcessor_authorMessageHeader',
  LlmChunkProcessor_semanticSearchRegex = 'LlmChunkProcessor_semanticSearchRegex',
  LlmChunkProcessor_authorMessageRegex = 'LlmChunkProcessor_authorMessageRegex',
  LlmChunkProcessor_finalAnswerInstruction = 'LlmChunkProcessor_finalAnswerInstruction',
  // RAG Application constants
  RagApplication_telegramMessageIdentifier = 'RagApplication_telegramMessageIdentifier',
  // RAG Searcher constants
  RagSearcher_metadataSeparator = 'RagSearcher_metadataSeparator',
}

export const getConstant = (key: GetConstantKey) => {
  const path = resolve(process.cwd(), '..', 'constants', `${key}.txt`);
  console.log(path);
  return readFileSync(path, 'utf-8');
};
