-- RenameIndex
ALTER INDEX "IDX_CHAT_LLM_MODELS__REQUEST_ID" RENAME TO "IDX_CHAT_LLM_MODELS__LAST_REQUEST_ID";

-- RenameIndex
ALTER INDEX "IDX_CHAT_LLM_MODELS__STATUS_REQUEST_ID" RENAME TO "IDX_CHAT_LLM_MODELS__STATUS_LAST_REQUEST_ID";
